= Robert Bennett's Projects
:description: Highlighted projects of mine.

[.lead]
This page is a portal to other GitHub pages of mine:

Collagen: The Collage Generator::
[.repo-link]##{repo-clgn}[icon:github[]{name-clgn}]##
+
Collagen is a program that takes as input a folder containing zero or more image files (`.jpeg`, `.png`, etc.) and a JSON manifest file describing the layout of these images along with SVG components such as shapes and text, and produces as output a single SVG file with all assets embedded.

Advent of Code 2021::
[.repo-link]##{repo-aoc-2021}[icon:github[]{name-aoc-2021}]##
+
https://rben01.github.io/advent_of_code_2021/docs/advent_of_code_2021.html[My solutions] to the 25 https://adventofcode.com/2021[Advent of Code 2021] problems.
This was fun and challenging and a great way for me to learn Rust.

https://rben01.github.io/covid19/[COVID-19/Coronavirus Tracker]::
[.repo-link]##{repo-covid}[icon:github[]{name-covid}]##
+
A collection of graphs displaying how coronavirus has spread throughout the world and in particular throughout the US. +
The data was ingested with {resource-link-pandas}, the graphics were built with {resource-link-d3}, and the site itself was written with {resource-link-asciidoctor}.

{url-trivia-page}[Quarantine Trivia]::
[.repo-link]##{repo-trivia}[icon:github[]{name-trivia}]##
+
A collection of trivia games I put together to give friends something to play while hanging out virtually during the coronavirus pandemic. The games are available {url-trivia-page}[here].
