site:
  robots: allow
  start_page: main::index.adoc
  title: Robert Bennett
  url: https://rltb.me

content:
  sources:
    - url: ./content/main
      branches: HEAD
    - url: ./content/blog
      branches: HEAD
    - url: ./content/projects
      branches: HEAD

ui:
  bundle:
    url: ./site-ui
    start_path: src
  supplemental_files: ./site-ui/static

urls:
  html_extension_style: drop

antora:
  extensions:
    - require: "@antora/lunr-extension"

asciidoc:
  attributes:
    author: Robert Bennett
    user: rben01
    github-site: link:https://github.com
    github-user: "{github-site}/{user}"
    github-icon-in-link: icon:github[]{nbsp},role="no-underline"
    email: pass:a,q[[.repo-link]##{github-user}[icon:github[]{user}]##]
    hide-uri-scheme:
    url-trivia-page: link:{github-pages-root}/quarantine-trivia
