[site]
	robots = "allow"
	start_page = "main::index.adoc"
	title = "Robert Bennett"
	url = "https://rltb.me"

[[content.sources]]
	branches = "HEAD"
	url = "./content/main"

[[content.sources]]
	branches = "HEAD"
	url = "./content/blog"

[ui.bundle]
	snapshot = true
	url = "https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable"

[urls]
	html_extension_style = "drop"

[[antora.extensions]]
	require = '@antora/lunr-extension'
