site:
  robots: allow
  start_page: home::index.adoc
  title: Robert Bennett
  url: https://rltb.me

content:
  sources:
    - url: ./content/home
      branches: HEAD
    - url: ./content/blog
      branches: HEAD
    - url: ./content/projects
      branches: HEAD

ui:
  bundle:
    url: ./site-ui
    start_path: src
  supplemental_files: ./site-ui/static

urls:
  html_extension_style: drop

antora:
  extensions:
    - require: "@antora/lunr-extension"

asciidoc:
  attributes:
    nbsp: ""
    author: Robert Bennett
    user: rben01
    github-site: link:https://github.com
    github-user: "{github-site}/{user}"
    github-icon-in-link: icon:github[]&#xa0;,role="no-underline"
    email: pass:a,q[[.repo-link]##{github-user}[icon:github[]{user}]##]
