site:
  robots: allow
  title: Robert Bennett
  url: /

content:
  sources:
    - url: ./content
      start_paths:
        - home
        - blog
        - projects
      branches: HEAD

ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/rben01/antora-ui/releases/download/v0.4.0/ui-bundle.zip
    # url: ../Antora Theme/src
  supplemental_files:
    - path: about.txt
      contents: ./static/about.txt
    - path: android-chrome-192x192.png
      contents: ./static/android-chrome-192x192.png
    - path: android-chrome-512x512.png
      contents: ./static/android-chrome-512x512.png
    - path: apple-touch-icon.png
      contents: ./static/apple-touch-icon.png
    - path: favicon-16x16.png
      contents: ./static/favicon-16x16.png
    - path: favicon-32x32.png
      contents: ./static/favicon-32x32.png
    - path: favicon.ico
      contents: ./static/favicon.ico
    - path: site.webmanifest
      contents: ./static/site.webmanifest

urls:
  html_extension_style: drop

antora:
  extensions:
    - require: "@antora/lunr-extension"

asciidoc:
  attributes:
    nbsp: ""
    icons: font
    author: Robert Bennett
    user: rben01
    github-site: link:https://github.com
    github-user: "{github-site}/{user}"
    github-icon-in-link: icon:github[]&#xa0;,role="no-underline"
    email: pass:a,q[[.repo-link]##{github-user}[icon:github[]{user}]##]
