[site]
	start_page = "component-b::index.adoc"
	title = "Robert Bennett"
	url = "https://rltb.me"

[[content.sources]]
	url = "./docs"

[ui.bundle]
	snapshot = true
	url = "https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable"
