site:
  robots: allow
  title: Robert Bennett
  url: /

content:
  sources:
    - url: ./content
      start_paths:
        - home
        - articles
        - projects
      branches: HEAD

ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/rben01/antora-ui/releases/download/v0.6.0/ui-bundle.zip
    # url: ../Antora Theme/src
  supplemental_files:
    - path: about.txt
      contents: ./static/about.txt
    - path: android-chrome-192x192.png
      contents: ./static/android-chrome-192x192.png
    - path: android-chrome-512x512.png
      contents: ./static/android-chrome-512x512.png
    - path: apple-touch-icon.png
      contents: ./static/apple-touch-icon.png
    - path: favicon-16x16.png
      contents: ./static/favicon-16x16.png
    - path: favicon-32x32.png
      contents: ./static/favicon-32x32.png
    - path: favicon.ico
      contents: ./static/favicon.ico
    - path: site.webmanifest
      contents: ./static/site.webmanifest

urls:
  html_extension_style: drop

antora:
  extensions:
    - require: "@antora/lunr-extension"

asciidoc:
  attributes:
    icons: font
    author: Robert Bennett
    user: rben01
    github-site: https://github.com
    github-user: "{github-site}/{user}"
    email: pass:a,q[[.repo-link]##{github-user}[icon:github[]{user}]##]
    github-icon-in-link: icon:github[]&#xa0;,role="no-underline"
    github-pages-base-url: https://rben01.github.io
    name-covid: "{user}/covid19"
    repo-covid: "{github-site}/{name-covid}"
    name-trivia: "{user}/quarantine-trivia"
    repo-trivia: "{github-site}/{name-trivia}"
    name-clgn: "{user}/collagen"
    repo-clgn: "{github-site}/{name-clgn}"
    name-aoc-2021: "{user}/advent_of_code_2021"
    repo-aoc-2021: "{github-site}/{name-aoc-2021}"
    name-aoc-2022: "{user}/advent_of_code_2022"
    repo-aoc-2022: "{github-site}/{name-aoc-2022}"
    resource-link-rust: link:https://www.rust-lang.org[Rust^]
    resource-link-rust-analyzer: link:https://rust-analyzer.github.io[rust-analyzer^]
    resource-link-asciidoctor: link:https://asciidoctor.org[AsciiDoctor^]
    resource-link-beamer: link:https://ctan.org/pkg/beamer[beamer^]
    resource-link-pandas: link:https://pandas.pydata.org[Pandas^]
    resource-link-matplotlib: link:https://matplotlib.org[Matplotlib^]
    resource-link-bokeh: link:https://bokeh.org[Bokeh^]
    resource-link-d3: link:https://d3js.org[d3^]
    resource-link-ffmpeg: link:https://ffmpeg.org[ffmpeg^]
    resource-link-latex: link:https://www.latex-project.org[LaTeX^]
    resource-link-threejs: link:https://threejs.org/[Three.js^]
    github-logo-role: .site-logo.github-logo.github-repo-logo
    url-trivia-page: "{github-pages-base-url}/quarantine-trivia"
