[site]
	robots = "allow"
	start_page = "main::index.adoc"
	title = "Robert Bennett"
	url = "https://rltb.me"

[[content.sources]]
	branches = "HEAD"
	url = "./content/main"

[[content.sources]]
	branches = "HEAD"
	url = "./content/blog"

[ui.bundle]
	snapshot = true
	url = "./site-ui/ui-bundle"

[urls]
	html_extension_style = "drop"

[[antora.extensions]]
	require = '@antora/lunr-extension'
