= Robert Bennett's Projects
:author: Robert Bennett
:user: rben01
:github-site: link:https://github.com
:github-repo: {github-site}/{user}
:github-icon-in-link: icon:github[]{nbsp},role="no-underline"
:email: {github-repo}[{github-icon-in-link}]{github-repo}[{user}]
:docinfo: shared-head
:description: My GitHub Pages home page, linking to my other pages.
:stylesheet: styles/homepage.css
:nofooter:
:linkcss!:
:icons: font
:hide-uri-scheme:
:name-covid: {user}/covid19
:repo-covid: {github-site}/{name-covid}
:name-quarantine-music-trivia: {user}/quarantine-music-trivia
:repo-quarantine-music-trivia: {github-site}/{name-quarantine-music-trivia}
:name-quarantine-movie-trivia: {user}/quarantine-movie-trivia
:repo-quarantine-movie-trivia: {github-site}/{name-quarantine-movie-trivia}
:asciidoctor-link: link:https://asciidoctor.org[AsciiDoctor]

// best themes: adoc-rubygems, boot-readable, boot-cosmo, plain
// (homepage.css is based off adoc-rubygems)
// Good favicon fonts: Asar
// https://favicon.io/favicon-generator/?t=rb&ff=Abel&fs=120&fc=%23011&b=rounded&bc=%23FFF


[.lead]
This page is a portal to other GitHub pages of mine:


https://rben01.github.io/covid19/[COVID-19/Coronavirus Tracker]::
{repo-covid}[{github-icon-in-link}]{repo-covid}[{name-covid}] +
A collection of graphs displaying how coronavirus has spread throughout the world and in particular throughout the US. +
The graphs were built with https://pandas.pydata.org[Pandas] and https://matplotlib.org[Matplotlib], the site with {asciidoctor-link}.
Quarantine Trivia::
__A collection of trivia games I put together to give friends something to play while hanging out virtually during the coronavirus pandemic. The different variations are below.__
https://rben01.github.io/quarantine-music-trivia/[Quarantine __Name That Tune__ Trivia]:::
{repo-quarantine-music-trivia}[{github-icon-in-link}]{repo-quarantine-music-trivia}[{name-quarantine-music-trivia}] +
Like trivia, but the questions are all audio clips from well-known songs with prompts such as "`Name the song`", "`Name the album`", and "`What movie had this song as the theme?`". +
The site was built by parsing a list of questions and generating {asciidoctor-link} source. Music clips created with https://ffmpeg.org[ffmpeg].
+
[WARNING]
--
The site does not discard media that has been scrolled out of view, so it _will_ use a lot of memory.
Refreshing should purge memory, but I recommend only playing on desktop for the time being.
Hopefully I'll get around to fixing this at some point.
--
https://rben01.github.io/quarantine-movie-trivia/LaTeX/movie_trivia.pdf[Quarantine Movie Trivia]:::
{repo-quarantine-movie-trivia}[{github-icon-in-link}]{repo-quarantine-movie-trivia}[{name-quarantine-movie-trivia}] +
A simpler trivia game -- just Q's and A's about movies.
The file is a PDF slideshow and should work fine in any web browser or PDF viewer, although it's recommended you use a viewer that can flip through the pages without scrolling.
You can use the left sidebar of the PDF to navigate; everything in it is a link. +
The PDF was built by parsing a Q-and-A list and generating LaTeX (http://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf[beamer]) source.
