= Robert Bennett's Projects
:author: Robert Bennett
:user: rben01
:github-site: link:https://github.com
:github-user: {github-site}/{user}
:github-icon-in-link: icon:github[]{nbsp},role="no-underline"
:email: {github-user}[{github-icon-in-link}]{github-user}[{user}]
:docinfo: shared-head
:description: My GitHub Pages home page, linking to my other pages.
:stylesheet: styles/homepage.css
:nofooter:
:linkcss!:
:icons: font
:hide-uri-scheme:
:resource-link-asciidoctor: link:https://asciidoctor.org[AsciiDoctor]
:resource-link-beamer: http://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf[beamer]
:resource-link-pandas: https://pandas.pydata.org[Pandas]
:resource-link-matplotlib: https://matplotlib.org[Matplotlib]
:resource-link-bokeh: https://bokeh.org[Bokeh]
:resource-link-ffmpeg: https://ffmpeg.org[ffmpeg]
:name-covid: covid19
:repo-covid: {github-user}/{name-covid}
:github-pages-root: https://rben01.github.io
:name-quarantine-music-trivia: quarantine-music-trivia
:repo-quarantine-music-trivia: {github-user}/{name-quarantine-music-trivia}
:name-quarantine-movie-trivia: quarantine-movie-trivia
:repo-quarantine-movie-trivia: {github-user}/{name-quarantine-movie-trivia}
:name-quarantine-general-trivia-2: quarantine-general-trivia-2
:repo-quarantine-general-trivia-2: {github-user}/{name-quarantine-general-trivia-2}
:name-quarantine-trivia-5: quarantine-trivia-5
:repo-quarantine-trivia-5: {github-user}/{name-quarantine-trivia-5}
:created-with-beamer-note: The PDF was built by parsing a Q-and-A list and generating LaTeX ({resource-link-beamer}) source.
:bonus-section-note: and a bonus section comprised of one challenging question from each of these categories.

// best themes: adoc-rubygems, boot-readable, boot-cosmo, plain
// (homepage.css is based off adoc-rubygems)
// Good favicon fonts: Asar
// https://favicon.io/favicon-generator/?t=rb&ff=Abel&fs=120&fc=%23011&b=rounded&bc=%23FFF


[.lead]
This page is a portal to other GitHub pages of mine:


https://rben01.github.io/covid19/[COVID-19/Coronavirus Tracker]::
{repo-covid}[{github-icon-in-link}]{repo-covid}[{name-covid}] +
A collection of graphs displaying how coronavirus has spread throughout the world and in particular throughout the US. +
The graphs were built with {resource-link-pandas} and {resource-link-bokeh}, the site with {resource-link-asciidoctor}.
Quarantine Trivia::
__A collection of trivia games I put together to give friends something to play while hanging out virtually during the coronavirus pandemic. The different variations are below. Trivia 1 was done in an ad-hoc manner and is not available online.__

{github-pages-root}/quarantine-music-trivia/[__Name That Tune__ Trivia]:::
{repo-quarantine-music-trivia}[{github-icon-in-link}]{repo-quarantine-music-trivia}[{name-quarantine-music-trivia}] +
Like trivia, but the questions are all audio clips from well-known songs with prompts such as "`Name the song`", "`Name the album`", and "`What movie had this song as the theme?`". +
The site was built by parsing a list of questions and generating {asciidoctor-link} source. Music clips created with {resource-link-ffmpeg}.
+
[WARNING]
--
The site does not discard media that has been scrolled out of view, so it _will_ use a lot of memory.
Refreshing should purge memory, but I recommend only playing on desktop for the time being.
Hopefully I'll get around to fixing this at some point.
--

{github-pages-root}/quarantine-movie-trivia/LaTeX/movie_trivia.pdf[Movie Trivia]:::
{repo-quarantine-movie-trivia}[{github-icon-in-link}]{repo-quarantine-movie-trivia}[{name-quarantine-movie-trivia}] +
A simpler trivia game -- just Q's and A's about movies.
The file is a PDF slideshow and should work fine in any web browser or PDF viewer, although it's recommended you use a viewer that can flip through the pages without scrolling.
You can use the left sidebar of the PDF to navigate; everything in it is a link. +
{created-with-beamer-note}

{github-pages-root}/quarantine-general-trivia-2/LaTeX/general_trivia.pdf[Trivia 4]:::
{repo-quarantine-general-trivia-2}[{github-icon-in-link}]{repo-quarantine-general-trivia-2}[{name-quarantine-general-trivia-2}] +
General knowledge trivia with the following categories: sports, plays and playwrights, women in American history, science, plants and animals, U.S. presidents, Dr. Anthony Fauci, famous paintings (identify the artist), Canada, world landmarks, {bonus-section-note} +
{created-with-beamer-note}

{github-pages-root}/quarantine-trivia-5/LaTeX/general_trivia.pdf[Trivia 5]:::
{repo-quarantine-trivia-5}[{github-icon-in-link}]{repo-quarantine-trivia-5}[{name-quarantine-trivia-5}] +
General knowledge trivia with the following categories: logos, cocktails, superheroes, New York City, more plants and animals, geography, real name/stage name, what are they saying about me?, ancient civilizations, TV, {bonus-section-note} +
{created-with-beamer-note}
