= Robert Bennett's Page
:author: Robert Bennett
:email: https://github.com/rben01[GitHub Profile]
:description: My GitHub Pages home page, linking to my other pages.
:stylesheet: styles/adoc-rubygems.css
:nofooter:
:hide-uri-scheme:
:repo-covid: rben01/covid19
:repo-quarantine-music-trivia: rben01/quarantine-music-trivia

// best themes: adoc-rubygems, boot-readable, boot-cosmo, plain

[.lead]
This page is just a portal to other GitHub pages of mine:


[pass]
++++
<style>
html * { font-family: "Tahoma", "Helvetica", sans-serif !important; }
.hdlist1 { font-size: 20px }
a { color: #00609a !important; text-decoration: underline !important; }
body {
     max-width: 800px;
     margin: 0px auto;
	 padding: 5px 15px white;
     }
</style>
++++


https://rben01.github.io/covid19/[COVID-19/Coronavirus Tracker]::
	A collection of graphs displaying how coronavirus has spread throughout the world. +
	*GitHub repo*: https://github.com/{repo-covid}[{repo-covid}]
https://rben01.github.io/quarantine-music-trivia/[Quarantine _Name That Tune_]::
	A trivia game I put together to give friends something to play when hanging out virtually during the coronavirus pandemic. Like trivia, but the questions are all audio clips from well-known songs with prompts such as "`Name the song.`" and "`What movie had this song as the theme?`". +
	*GitHub repo*: https://github.com/{repo-quarantine-music-trivia}[{repo-quarantine-music-trivia}]
