= Robert Bennett's Projects
:author: Robert Bennett
:email: https://github.com/rben01[GitHub: rben01]
:description: My GitHub Pages home page, linking to my other pages.
:stylesheet: styles/homepage.css
:favicon: favicon_128x128.png
:nofooter:
:icons: font
:hide-uri-scheme:
:repo-covid: rben01/covid19
:repo-quarantine-music-trivia: rben01/quarantine-music-trivia

// best themes: adoc-rubygems, boot-readable, boot-cosmo, plain
// Good favicon fonts: macondo, habibi

[.lead]
This page is just a portal to other GitHub pages of mine:



https://rben01.github.io/covid19/[COVID-19/Coronavirus Tracker]::
icon:github[] {nbsp} https://github.com/{repo-covid}[{repo-covid}] +
A collection of graphs displaying how coronavirus has spread throughout the world and in particular throughout the US. +
https://rben01.github.io/quarantine-music-trivia/[Quarantine _Name That Tune Trivia_]::
icon:github[] {nbsp} https://github.com/{repo-quarantine-music-trivia}[{repo-quarantine-music-trivia}] +
A trivia game I put together to give friends something to play when hanging out virtually during the coronavirus pandemic. Like trivia, but the questions are all audio clips from well-known songs with prompts such as "`Name the song.`" and "`What movie had this song as the theme?`".
+
[WARNING]
--
The site makes no attempt to discard videos that have been scrolled out of view, so it _will_ use a lot of memory. Refreshing should purge memory, but I recommend only playing on desktop for the time being. Hopefully I'll get around to fixing this at some point.
--
+
