= Quarantine Trivia
include::shared_attributes.asciidoc[]
:github-profile: link:https://github.com/rben01
:github-repo: {github-profile}/covid19
:github-icon-in-link: icon:github[]{nbsp},role="no-underline"
:email: https://rben01.github.io/[Other Projects,role="prominent-link"] {nbsp}/{nbsp} {github-profile}[{github-icon-in-link}]{github-profile}[rben01,role="prominent-link"]
:description: A collection of trivia games created to pass the time with friends during the COVID-19 quarantine.
:name-quarantine-music-trivia: quarantine-music-trivia
:repo-quarantine-music-trivia: {github-user}/{name-quarantine-music-trivia}
:name-quarantine-movie-trivia: quarantine-movie-trivia
:repo-quarantine-movie-trivia: {github-user}/{name-quarantine-movie-trivia}
:name-quarantine-general-trivia-2: quarantine-general-trivia-2
:repo-quarantine-general-trivia-2: {github-user}/{name-quarantine-general-trivia-2}
:name-quarantine-trivia-5: quarantine-trivia-5
:repo-quarantine-trivia-5: {github-user}/{name-quarantine-trivia-5}
:name-quarantine-trivia-6: quarantine-trivia-6
:repo-quarantine-trivia-6: {github-user}/{name-quarantine-trivia-6}
:name-quarantine-trivia-7: quarantine-trivia-7
:repo-quarantine-trivia-7: {github-user}/{name-quarantine-trivia-7}
:name-quarantine-trivia-8: quarantine-trivia-8
:repo-quarantine-trivia-8: {github-user}/{name-quarantine-trivia-8}
:bonus-section-note: and a bonus section comprised of one challenging question from each of these categories.

[.lead]
A collection of trivia games I put together to give friends something to play while hanging out virtually during the coronavirus pandemic.

Except for the music trivia game, the games are all distributed as PDFs and should work fine in any web browser or PDF viewer.
However, it's recommended that you use a viewer that can flip through the pages by pressing the arrow keys in order to avoid scrolling.
You can use the sidebars of the PDFs to navigate between rounds and questions; everything in them is a link. +
Each PDF was built by parsing a Q-and-A list and generating {resource-link-latex}/{resource-link-beamer} source. +
__Trivia 1 was done in an ad-hoc manner and is not available online.__


{github-pages-root}/{name-quarantine-music-trivia}/[__Name That Tune__ Trivia]:::
{repo-quarantine-music-trivia}[{github-icon-in-link}]{repo-quarantine-music-trivia}[{name-quarantine-music-trivia}] +
The questions are all audio clips from well-known songs with prompts such as "`Name the song`", "`Name the album`", and "`What movie had this song as the theme?`". +
The site was built by parsing a list of questions and generating {resource-link-asciidoctor} source. Music clips created with {resource-link-ffmpeg}.
+
[WARNING]
--
The site does not discard media that has been scrolled out of view, so it _will_ use a lot of memory.
Refreshing should purge memory, but I recommend only playing on desktop for the time being.
Hopefully I'll get around to fixing this at some point.
--

{github-pages-root}/{name-quarantine-movie-trivia}/LaTeX/movie_trivia.pdf[Movie Trivia]:::
{repo-quarantine-movie-trivia}[{github-icon-in-link}]{repo-quarantine-movie-trivia}[{name-quarantine-movie-trivia}] +
A simpler trivia game -- just Q's and A's about movies.

{github-pages-root}/{name-quarantine-general-trivia-2}/LaTeX/general_trivia.pdf[Trivia 4]:::
{repo-quarantine-general-trivia-2}[{github-icon-in-link}]{repo-quarantine-general-trivia-2}[{name-quarantine-general-trivia-2}] +
__This was the second general trivia game, but the fourth trivia game overall.__ +
General knowledge trivia with the following categories: sports, plays and playwrights, women in American history, science, plants and animals, U.S. presidents, Dr. Anthony Fauci, famous paintings (identify the artist), Canada, world landmarks, {bonus-section-note}

{github-pages-root}/{name-quarantine-trivia-5}/LaTeX/general_trivia.pdf[Trivia 5]:::
{repo-quarantine-trivia-5}[{github-icon-in-link}]{repo-quarantine-trivia-5}[{name-quarantine-trivia-5}] +
General knowledge trivia with the following categories: logos, cocktails (name the drink whose recipe is shown), superheroes, New York City, more plants and animals, geography, real name/stage name, what are they saying about me?, ancient civilizations, TV, {bonus-section-note}

{github-pages-root}/{name-quarantine-trivia-6}/LaTeX/general_trivia.pdf[Trivia 6]:::
{repo-quarantine-trivia-6}[{github-icon-in-link}]{repo-quarantine-trivia-6}[{name-quarantine-trivia-6}] +
General knowledge trivia with the following categories: weather, word origins, Broadway musical names from song titles, dog breeds, Disney, national parks, Rome, books that had a big impact, inventors and inventions, California, {bonus-section-note}

{github-pages-root}/{name-quarantine-trivia-7}/LaTeX/general_trivia.pdf[Trivia 7]:::
{repo-quarantine-trivia-7}[{github-icon-in-link}]{repo-quarantine-trivia-7}[{name-quarantine-trivia-7}] +
General knowledge trivia with the following categories: album by album art, France, airport codes, big dates in history, gangsters in fact and fiction, holidays and observances, all the cool kids are texting about South Dakota, pastries, explorers, products and companies by their slogans, {bonus-section-note}

{github-pages-root}/{name-quarantine-trivia-8}/LaTeX/general_trivia.pdf[Trivia 8]:::
{repo-quarantine-trivia-8}[{github-icon-in-link}]{repo-quarantine-trivia-8}[{name-quarantine-trivia-8}] +
General knowledge trivia with the following categories: Colleges and Universities, Horse Racing, The Constitution, It happened in 2010, Under the Sea, Myths and Legends, Mexico, Our Friendly Neighbor to the South, Famous Buildings, Nobel Prize Winners, The Beatles {bonus-section-note}
