= Home
:description: The homepage of https://rltb.me

Hi, I'm Robert.
I'm a web developer and data analyst based in New York City.
I focus on making complex ideas tangible and easily understood.
My favorite languages for this job are {resource-link-rust} for building long-term data pipelines, thanks to the fantastic {resource-link-polars-rs} library; {resource-link-d3} and {resource-link-vega-lite-combined} for building browser-based visualizations; and {resource-link-julia}, for ad-hoc analysis and visualization.

Outside of work I enjoy {github-user}/collagen[writing] {github-user}/advent_of_code_2021[more] {github-user}/advent_of_code_2022[Rust], reading, taking photographs, and browsing https://fonts.google.com[Google Fonts].

[.desktop-instructions]
You can navigate using the left sidebar, or use the search bar in the top right.
The header bar also contains external links, including my https://github.com/rben01[GitHub profile^].

[.mobile-instructions]
You can navigate using the [.ui-icon.nav-menu-icon]#{blank}# menu in the top left, or use the search bar in the hamburger menu in the top right.
External links are also available in the hamburger menu.
